server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${URL_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: classpath:logging/logback.xml

