server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${URL_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASSWORD_DATABASE}
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: classpath:logging/logback.xml


aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  cognito:
    region: ${AWS_COGNITO_REGION}
    cliendId: ${AWS_COGNITO_CLIEND_ID}
    userPoolId : ${AWS_COGNITO_USER_POOL_ID}

